version: "3.3"

services:
 
  web:

    image: garypu445/nginx:latest

    deploy:

      replicas: 1

      restart_policy:

        condition: on-failure

    ports:
      #- "80:80"
      #- "443:443"
      - target: 80
        published: 80
        protocol: tcp
        mode: host

      - target: 443
        published: 443
        protocol: tcp
        mode: host

    volumes:
      - ./etc/nginx:/etc/nginx/

    networks:

      - webnet


networks:

  webnet:


